name: Check Amplify Deployment Status

on:
  workflow_dispatch:  # Trigger manually
  # You can also set other triggers like push, pull_request, etc.

jobs:
  check-status:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1  # Update with your AWS region

    - name: Install AWS CLI
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install

    - name: Check Amplify Status
      run: |
        APP_ID="d29xsq6gw0im14"
        BRANCH_NAME="master"
        
        # Fetch latest job for the given app and branch
        LATEST_JOB=$(aws amplify list-jobs --app-id $APP_ID --branch-name $BRANCH_NAME --max-results 1 --query 'jobSummaries[0].jobId' --output text)
        
        # Fetch job status
        JOB_STATUS=$(aws amplify get-job --app-id $APP_ID --branch-name $BRANCH_NAME --job-id $LATEST_JOB --query 'job.summary.status' --output text)
        
        echo "Latest Job ID: $LATEST_JOB"
        echo "Latest Job Status: $JOB_STATUS"
        
        # Optionally, fail the workflow if the status is not 'SUCCEEDED'
        if [[ "$JOB_STATUS" != "SUCCEEDED" ]]; then
          exit 1
        fi
